/*
 * Hugh Tuckwell & Samuel Duffy
 * 07/06/2022
 * The Credits Window, Used to simply display the Credits over a Casino Background,
 * Whenever the user decides to go back to the First Window, they Can
 */
package duffytuckwellfinalproject;

// Import ImageIcon to display the background
import javax.swing.ImageIcon;


public class CreditsWindow extends javax.swing.JFrame {
    FirstWindow firstWindow; // Create an object for the firstWindow, to go back
    
    /**
     * The Constructor, used when the User decides to press the Credits button on
     * the first window, and switches to the credit window
     * @param m - the first window
     */
    public CreditsWindow(FirstWindow m) {
        initComponents();
        firstWindow = m;
        
        // Add and resize the background to the window
        ImageIcon bg = new ImageIcon("src/duffytuckwellfinalproject/images/Backgrounds/LuigiBackground.png");
        ImageIcon resizedBg = new ImageIcon(bg.getImage().getScaledInstance(640, 480, java.awt.Image.SCALE_SMOOTH));
        lblBackground.setIcon(resizedBg);
        
        // Add and resize a custom button to quit the window
        ImageIcon quit = new ImageIcon("src/duffytuckwellfinalproject/images/Buttons/Quit.png");
        ImageIcon resizedQuit = new ImageIcon(quit.getImage().getScaledInstance(120, 60, java.awt.Image.SCALE_SMOOTH));
        btnQuit.setIcon(resizedQuit);
        
        // Make sure the user cannot resize the window
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuit = new javax.swing.JButton();
        lblHugh = new javax.swing.JLabel();
        lblSam = new javax.swing.JLabel();
        lblFinn = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(645, 485));
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, 60));

        lblHugh.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        lblHugh.setForeground(new java.awt.Color(255, 255, 255));
        lblHugh.setText("Hugh Tuckwell - Base Game, Art Design, Main Menu");
        getContentPane().add(lblHugh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lblSam.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        lblSam.setForeground(new java.awt.Color(255, 255, 255));
        lblSam.setText("Samuel Duffy - Design, Art Design, Implementation, File Save");
        getContentPane().add(lblSam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        lblFinn.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        lblFinn.setForeground(new java.awt.Color(255, 255, 255));
        lblFinn.setText("Finn Fabian - Art Design ");
        getContentPane().add(lblFinn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * If the user presses the back button, we set the firstWindow to be visible,
     * and the credits window to be not visible, switching the two windows
     * @param evt 
     */
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        firstWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFinn;
    private javax.swing.JLabel lblHugh;
    private javax.swing.JLabel lblSam;
    // End of variables declaration//GEN-END:variables
}
